name: Tests Slack notifiactions local with sending a message

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout
      - name: Slack notification local
        uses: ./
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_mention_mapping_file: ./.github/slack-name-mapping.json
          slack_json: '{
            "username": "{{GITHUB_ACTOR}}",
            "text": "{{GITHUB_ACTOR}} made some notification",
            "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
            "channel": "your_channel",
            "blocks": [
            {
            "type": "section",
            "text": {
            "type": "mrkdwn",
            "text": "This is a test."
            }
            },
            {
            "type": "context",
            "elements": [
            {
            "type": "mrkdwn",
            "text": ":speech_balloon: Test Test Test>"
            }
            ]
            }
            ]
            }'
      - name: Slack failure notification
        if: ${{ failure() }}
        uses: ./
        with:
          slack_web_hook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_json: '{
            "username": "{{GITHUB_ACTOR}}",
            "text": "{{GITHUB_ACTOR}} made some notification",
            "icon_url": "{{CUSTOM_AUTHOR_PICTURE}}",
            "channel": "your_channel",
            "blocks": [
            {
            "type": "section",
            "text": {
            "type": "mrkdwn",
            "text": "This is a failure test."
            }
            },
            {
            "type": "context",
            "elements": [
            {
            "type": "mrkdwn",
            "text": ":speech_balloon: test test test"
            }
            ]
            }
            ]
            }'